### ISSUE TITLE
NPE with ... something?

### ISSUE THREAD

**Issue by briarss** [Mrthomas20121-Mods/EidolonTweaker#2]
https://gist.github.com/amoooooo/9d1dda2c73c8f19c1b18fd487fc46e97 ct log
https://gist.github.com/amoooooo/c81d0f6c6c572d65eeba7031789feadd script

ct chat error is just `null`.

**Comment by Mrthomas20121** [comment]
does the code inside the function works with the crafting table? i didn't do anything special, so if something break with the functions, it's on crafttweaker, not me.

**Comment by briarss** [comment]
yep, it works in the crafting table.

**Comment by Mrthomas20121** [comment]
weird
