### ISSUE TITLE
Usage in modpack with Eidolon Patches

### ISSUE THREAD

**Issue by HollishKid** [Mrthomas20121-Mods/EidolonTweaker#5]
I was trying to use this mod with [Eidolon Patches](https://www.curseforge.com/minecraft/mc-mods/eidolon-patches) instead of the original (now unmaintained) version of Eidolon. Curseforge client does not allow me to do so as the original Eidolon is a required dependency for this mod.

Do you think you could set original Eidolon to an optional dependency so that we can use this mod with Eidolon Patches?
Thanks for considering this!

**Comment by Mrthomas20121** [comment]
done for the latest uploaded file
